export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const FRONTEND_LOGOUT = 'FRONTEND_LOGOUT'
export const SET_TOKEN = 'SET_TOKEN'
export const CLEAR_TOKEN = 'CLEAR_TOKEN'
export const SET_ROLES = 'SET_ROLES'
export const FETCH_USER_INFO = 'FETCH_USER_INFO'
export const FETCH_USERS = 'FETCH_USERS'
export const SET_USER_INFO = 'SET_USER_INFO'
export const SET_COLLAPSE = 'SET_COLLAPSE'
export const SWITCH_USER_GROUP = 'SWITCH_USER_GROUP'

