export const FETCH_APPS = 'apps'
export const FETCH_APP = 'app'
export const FETCH_APP_INSTANCES = 'app-instances'
export const FETCH_APP_VERSIONS = 'app-versions'
export const FETCH_APP_CUR_VERSION = 'app-curVersion'
